version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672" #management # habilitado visualização no browser
      #- "15692:15692" #prometheus # desnecessário
      - "5672:5672" #amqp       # desnecessário